{{- if and .Values.auth.enabled .Values.auth.token (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kymaros.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kymaros.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.auth.token | quote }}
{{- end }}
