{{- if .Values.gatewayAPI.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "kymaros.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kymaros.labels" . | nindent 4 }}
  {{- with .Values.gatewayAPI.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml .Values.gatewayAPI.parentRefs | nindent 4 }}
  hostnames:
    {{- range .Values.gatewayAPI.hostnames }}
    - {{ . | quote }}
    {{- end }}
  rules:
    - matches:
        {{- toYaml .Values.gatewayAPI.matches | nindent 8 }}
      backendRefs:
        - name: {{ include "kymaros.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
