{{- if .Values.ingress.enabled -}}
{{- $host := .Values.ingress.dashboard.host -}}
{{- if .Values.api.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kymaros.fullname" . }}-dashboard
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kymaros.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.dashboard.tls.enabled }}
  tls:
    - hosts:
        - {{ $host | quote }}
      secretName: {{ .Values.ingress.dashboard.tls.secretName | default (printf "%s-dashboard-tls" (include "kymaros.fullname" .)) }}
  {{- end }}
  rules:
    - host: {{ $host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "kymaros.fullname" . }}-api
                port:
                  number: {{ .Values.api.port }}
{{- end }}
{{- end }}
