{{- if and .Values.api.enabled .Values.serviceAccountApi.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kymaros.apiServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kymaros.labels" . | nindent 4 }}
  {{- with .Values.serviceAccountApi.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
